replicaCount: 1
# v1.2.0-660ae95
image:
  registry: "ghcr.io"
  repository: "vladyslavPlaksa/kbot-telegram"
  pullPolicy: IfNotPresent # Дозволяє замінити образ за замовчуванням
  tag: v1.0.5-ef6300c
  os: linux
  arch: amd64
  parameter: go
# Додатково визначте секцію для токену TELE_TOKEN
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
  value: "7058543062:AAHAOJTkmVL9cxoLXgtwfK45LdCsPJxI-hE"
securityContext:
  privileged: true
